DROP TYPE USERSTATUS;
CREATE TYPE USERSTATUS AS ENUM ('Active', 'Suspended');
DROP TYPE JOBSTATUS;
CREATE TYPE JOBSTATUS AS ENUM ('Not Started', 'Success', 'Failed');
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID serial PRIMARY KEY,
    USERNAME VARCHAR (50) UNIQUE NOT NULL,
    PASSWORD VARCHAR (100) NOT NULL,
    DISPLAY_NAME VARCHAR (100) NOT NULL,
    STATUS USERSTATUS NOT NULL
);

DROP TABLE IF EXISTS JOBS;
CREATE TABLE JOBS (
    JOB_ID serial PRIMARY KEY,
    USER_ID INT NOT NULL,
    FILE_NAME VARCHAR(50) NOT NULL,
    FILE_PATH VARCHAR(200),
    STATUS JOBSTATUS NOT NULL,
    TRANSCRIPT JSON,
    FOREIGN KEY (USER_ID)
        REFERENCES "public".USERS (USER_ID)
);